name: Build daily MLST-AS PMTiles

on:
  schedule:
    - cron: "30 6 * * *"   # daily at 06:30 UTC
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install GDAL
        run: sudo apt-get update && sudo apt-get install -y gdal-bin

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install rio-pmtiles

      - name: Prepare folders
        run: mkdir -p work tiles

      # --- Configure your dataset ---
      - name: Build URL for today
        env:
          TARGET_HHMM: "1100"   # adjust if product is published at a different time
        run: |
          Y=$(date -u +%Y)
          M=$(date -u +%m)
          D=$(date -u +%d)
          TS="${Y}${M}${D}${TARGET_HHMM}"
          echo "STAMP=${TS}" >> $GITHUB_ENV
          echo "NETCDF_URL=https://datalsasaf.lsasvcs.ipma.pt/PRODUCTS/MSG/MLST-AS/NETCDF/${Y}/${M}/${D}/NETCDF4_LSASAF_MSG_MLST-AS_MSG-Disk_${TS}.nc" >> $GITHUB_ENV

      - name: Download NetCDF (auth)
        env:
          LSA_USER: ${{ secrets.LSA_USER }}
          LSA_PASS: ${{ secrets.LSA_PASS }}
          NETCDF_URL: ${{ env.NETCDF_URL }}
        run: |
          echo "Fetching: $NETCDF_URL"
          curl -fL -u "${LSA_USER}:${LSA_PASS}" "$NETCDF_URL" -o work/input.nc

      - name: Inspect subdatasets (for logs)
        run: gdalinfo work/input.nc | head -n 100

      - name: NetCDF -> GeoTIFF (native)
        run: |
          gdal_translate "NETCDF:\"work/input.nc\":MLST-AS" work/raw_native.tif -a_nodata 0 -unscale

      - name: Reproject to EPSG:3857
        run: gdalwarp -t_srs EPSG:3857 -r bilinear -dstalpha work/raw_native.tif work/merc.tif

      - name: Colorize (fixed ramp)
        run: |
          cat > work/ramp.txt << 'TXT'
          nv 0 0 0 0
          # value  R  G  B
          180  0   0 255
          200  0  64 255
          220  0 128 255
          240  0 191 191
          260  0 223 127
          280 64 223  64
          300 223 191 32
          320 255 128  0
          340 255   0  0
          TXT

          gdaldem color-relief work/merc.tif work/ramp.txt work/color.tif -alpha

      - name: GeoTIFF -> PMTiles
        run: rio pmtiles work/color.tif tiles/raster.pmtiles --zoom-levels 0..6

      - name: Commit & push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "build(pmtiles): MLST-AS daily refresh [skip ci]"
          file_pattern: tiles/raster.pmtiles
