name: Build daily CAB pixel shapefile

on:
  schedule:
    - cron: "0 17 * * *"   # daily at 17:00 UTC
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate GeoJSON
        env:
          # Change these if you want 06/12/18 instead of 00Z
          GDAS_CYCLE: "00"
        run: |
          python scripts/process_cab.py
     
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: tiles/drylines.geojson
          commit_message: "Update tiles/drylines.geojson (${{ github.run_id }})"
      
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: |
            database/cab_history.csv
          commit_message: "Update cab_history.csv (${{ github.run_id }})"
