name: Build daily rainbelt shapefile

on:
  schedule:
    - cron: "0 16 * * *"   # daily at 18:00 UTC
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate GeoJSON
        env:
          # Change these if you want 06/12/18 instead of 00Z
          GDAS_CYCLE: "00"
          AFRICA_GEOJSON_URL: "https://gist.githubusercontent.com/1310aditya/35b939f63d9bf7fbafb0ab28eb878388/raw/africa.json"
        run: |
          python scripts/process_rainbelt.py

      - name: Touch files to ensure they appear changed
        run: |
          touch belt.geojson
          touch database/rainbelthistory.csv

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: |
            tiles/belt.geojson
            database/rainbelthistory.csv
          commit_message: "Update belt.geojson + rainbelthistory.csv (${{ github.run_id }})"
