name: Build forecast data

on:
   schedule:
     - cron: "0 17 * * *"   # daily at 17:00 UTC
   workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate forecast data
        env:
          # Change these if you want 06/12/18 instead of 00Z
          GDAS_CYCLE: "00"
        run: |
          python scripts/generate_forecast_data.py
          
      - name: Touch files to ensure they appear changed
        run: touch database/rainbelt_lat.csv database/rainbelt_lat_north.csv database/rainbelt_lat_south.csv database/cab_gridcells.csv database/kd_gridcells.csv
      
      - name: Commit & push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "process forecast data"
          file_pattern: "database/*.csv"
