name: Plot forecast

on:
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate forecast plot
        env:
          # Change these if you want 06/12/18 instead of 00Z
          GDAS_CYCLE: "00"
        run: |
          python scripts/generate_hist_forecast_plot.py
          
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: |
            assets/tracker/history_and_forecast.png
          commit_message: "Update history_and_forecast.png (${{ github.run_id }})"
